# Generated by Django 5.1.1 on 2024-09-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipoestablecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('coordenada_x', models.DecimalField(decimal_places=8, max_digits=10)),
                ('coordenada_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('rango_de_precios', models.CharField(blank=True, max_length=5)),
                ('tipo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='api.tipoestablecimiento')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'db_table': 'establecimiento',
            },
        ),
    ]
