# Generated by Django 5.1.1 on 2024-09-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_etiqueta_alter_establecimiento_tipo_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establecimiento',
            options={},
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table=None,
        ),
    ]
