# Generated by Django 5.1.1 on 2024-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_etiquetaestablecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroEvento',
            fields=[
                ('id_genero_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_genero', models.CharField(max_length=40)),
                ('descripcion_genero', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
