# Generated by Django 5.1.1 on 2024-09-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_generoevento_alter_establecimiento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('id_genero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generoevento')),
            ],
        ),
    ]
