# Generated by Django 5.1.1 on 2024-09-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_entrada', models.CharField(max_length=20)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_entrada', models.CharField(max_length=100)),
                ('id_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
    ]
