# Generated by Django 5.1.1 on 2024-09-14 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('p_field', models.CharField(blank=True, max_length=50, null=True)),
                ('g_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_consumo', models.CharField(max_length=20)),
                ('precio_consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_consumo', models.CharField(blank=True, max_length=100)),
                ('id_establecimiento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
            ],
        ),
    ]
