# Generated by Django 5.1.1 on 2024-09-15 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_evento_asistido_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento'),
        ),
    ]
