# Generated by Django 5.1.1 on 2024-09-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_asistencia_id_evento_asistido_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionEvento',
            fields=[
                ('id_valoracion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateTimeField()),
                ('id_asistencia_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistencia')),
            ],
        ),
    ]
