# Generated by Django 5.1.1 on 2024-09-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_establecimiento_nro_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='em_ref',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
