# Generated by Django 5.1.1 on 2024-10-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_establecimiento_em_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/establecimientos/banners/'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/establecimientos/logos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/eventos/banners/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/eventos/logos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='g_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='p_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GaleriaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagen')),
            ],
            options={
                'unique_together': {('establecimiento', 'imagen')},
            },
        ),
        migrations.CreateModel(
            name='GaleriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagen')),
            ],
            options={
                'unique_together': {('evento', 'imagen')},
            },
        ),
        migrations.CreateModel(
            name='horariosEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.TextField(max_length=1)),
                ('inicio_atencion', models.TimeField()),
                ('fin_atencion', models.TimeField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
            ],
            options={
                'unique_together': {('establecimiento', 'dia')},
            },
        ),
    ]
